# Generated by Django 4.1.1 on 2022-09-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodenapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='profile_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
