# Generated by Django 4.1.1 on 2022-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodenapi', '0002_alter_builder_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lumber',
        ),
        migrations.AddField(
            model_name='project',
            name='lumber',
            field=models.ManyToManyField(related_name='projects', to='woodenapi.lumber'),
        ),
    ]
