# Generated by Django 4.1.1 on 2022-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodenapi', '0003_remove_project_lumber_project_lumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_started',
            field=models.DateField(null=True),
        ),
    ]
