# Generated by Django 4.1.1 on 2022-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodenapi', '0004_project_date_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='active',
        ),
    ]
